version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: claims_db
      POSTGRES_USER: claims_user
      POSTGRES_PASSWORD: claims_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claims_user -d claims_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Claims Lifecycle Application
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://claims_user:claims_password@postgres:5432/claims_db
      SESSION_SECRET: your-production-secret-key-change-this
      NODE_ENV: production
      PORT: 5000
    volumes:
      - evidence_files:/app/evidences
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  evidence_files: